

spring:
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    timeout: 1000ms
    jedis:
      pool:
        max-active: 20
        max-wait: -1ms
        max-idle: 10
        min-idle: 0

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/demo2?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8

server:
  port: 18080